### ISSUE TITLE
could not convert string to float: ''

### ISSUE THREAD

**Issue by amirh2079** [zhunhung/Python-SentiStrength#10]
I have written same code but somehow i'm getting this error

`Traceback (most recent call last):

  File "/Users/daniel/Desktop/programming/python/Challenge/tests/sentementsStarting.py", line 9, in <module>
    result = senti.getSentiment('str_arr', score='scale')

  File "/Users/daniel/opt/anaconda3/lib/python3.8/site-packages/sentistrength/__init__.py", line 41, in getSentiment
    senti_score = list(map(float, senti_score))

ValueError: could not convert string to float: ''`

**Comment by epura** [comment]
@amirh2079 I am getting the same

**Comment by glher** [comment]
I'm a bit late to the party, but here is my guess if you encounter this issue:

I imagine you used:

```
senti = PySentiStr()
senti.setSentiStrengthPath('/mypath/SentiStrength.jar')
```

However, you likely actually obtained the file "SentiStrengthCom.jar". So the wrapper cannot find the jar and fails on a different error. It may be worth adding a different error message when the path is set but the jar is not found.

**Comment by sgzapata** [comment]
I don't found file "sentistrength.jar" in   http://sentistrength.wlv.ac.uk/..... I can download the file "SentiStrength2.3Free" only. Can you help me?

**Comment by glher** [comment]
You will have to directly contact the research team in charge at the University of Wolverhampton for this, the Java version of SentiStrength is available for purchase or for academic purposes according to their website: "To use the Java version for research only (free), email from your academic email address."

**Comment by sgzapata** [comment]
Yes, I filled the form to academic purposes, but in the downloaded zip file not included the file "SentiStrength.jar" (includes SentiStrength2.3Free.exe)

**Comment by sanjeev077** [comment]
can someone please tell where can i get sentistrength.jar file

**Comment by amirh2079** [comment]
this is the file that i used in my project and it worked correctly:
https://drive.google.com/file/d/1_ndjC6zKYI09KNbvkpUiMWV3Q69PuLDh/view?usp=sharing

**Comment by glher** [comment]
I would recommend not posting the SentiStrength jar file in a public way like that, as it's supposed to be given by the original developers based on academic requests and the license may not permit this sharing directly without the express authorization from Prof Michael Thelwall for example.

**Comment by amirh2079** [comment]
sorry, you are right

**Comment by sutravekruttika** [comment]
@amirh2079 can you please help me resolve this issue. I get the same error as yours. Also, I am using the correct jar file name. Following is my code and error:

from sentistrength import PySentiStr
senti = PySentiStr()
senti.setSentiStrengthPath('drive/My Drive/SentiStrength.jar')
senti.setSentiStrengthLanguageFolderPath('drive/My Drive/SentiStrengthData/')
str_arr = ['What a lovely day', 'What a bad day']
result = senti.getSentiment(str_arr, score='binary')

Error:

ValueError Traceback (most recent call last)
in ()
1 str_arr = ['What a lovely day', 'What a bad day']
----> 2 result = senti.getSentiment(str_arr, score='binary')

/usr/local/lib/python3.7/dist-packages/sentistrength/init.py in getSentiment(self, df_text, score)
39 senti_score = stdout_text.split(' ')
40
---> 41 senti_score = list(map(float, senti_score))
42
43 senti_score = [int(i) for i in senti_score]

ValueError: could not convert string to float:

**Comment by zhunhung** [comment]
This error happens when you have a bad path for your SentiStrengthData folder. Do double check if it is correct. I have fixed the error handling, sorry about that
