### ISSUE TITLE
I still get this error - could not convert string to float: 

### ISSUE THREAD

**Issue by sutravekruttika** [zhunhung/Python-SentiStrength#12]
I am working in Jupyter Notebook, following your example. I have the jar file and SentiSrengthData folder. However, I get error. Following is my code and error:
 
from sentistrength import PySentiStr
senti = PySentiStr()
senti.setSentiStrengthPath('drive/My Drive/SentiStrength.jar')
senti.setSentiStrengthLanguageFolderPath('drive/My Drive/SentiStrengthData/')
str_arr = ['What a lovely day', 'What a bad day']
result = senti.getSentiment(str_arr, score='binary')

Error:

ValueError                                Traceback (most recent call last)
<ipython-input-19-2953167ce69c> in <module>()
      1 str_arr = ['What a lovely day', 'What a bad day']
----> 2 result = senti.getSentiment(str_arr, score='binary')

/usr/local/lib/python3.7/dist-packages/sentistrength/__init__.py in getSentiment(self, df_text, score)
     39         senti_score = stdout_text.split(' ')
     40 
---> 41         senti_score = list(map(float, senti_score))
     42 
     43         senti_score = [int(i) for i in senti_score]

ValueError: could not convert string to float:

**Comment by theproj98** [comment]
Have you managed to fix this error? I get the same error.

**Comment by sutravekruttika** [comment]
No, I have not. I am waiting for the author to respond.

Kruttika

**Comment by zhunhung** [comment]
Hi @sutravekruttika ,
I have discovered that the issue lies with:
`senti.setSentiStrengthLanguageFolderPath('drive/My Drive/SentiStrengthData/')`

I have added proper error handling in the new version. Please double check that your file path is correct, otherwise you'll get such an error

**Comment by sutravekruttika** [comment]
@zhunhung Thank you. I was able to run without any error. Indeed, the issue was with the file path. Thank you again.
