### ISSUE TITLE
Output options

### ISSUE THREAD

**Issue by farzinghanbari** [zhunhung/Python-SentiStrength#3]
Your wrapper only calculates **_Scale and Binary_** score.
So what about **Dual and Trinary** scores?
Are you planning on adding those outputs too?
What about different domains like Politics, Movies, and so on?

**Comment by zhunhung** [comment]
Hi @farzinghanbari , I've added Dual and Trinary. Thank you for pointing that out. As for domains, I'll need to find the domain-specific words to add them in.
