### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by onlymicky** [zhunhung/Python-SentiStrength#5]
Dear author,
when I ran  a sample test ('what a lovely day'), it turned out that:

 `  File "C:\Users\Xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sentistrength\__init__.py", line 40, in getSentiment
    senti_score = list(map(float, senti_score))
ValueError: could not convert string to float:`

Could you please tell me how to fix this error ? 
Thank you

**Comment by shahmohamadi** [comment]
I got same error:
`<class 'tuple'>: (<class 'ValueError'>, ValueError("could not convert string to float: 'Could'",), <traceback object at `0x7f28b7585c08>)``

**Comment by shahmohamadi** [comment]
> Dear author,
> when I ran a sample test ('what a lovely day'), it turned out that:
> 
> ` File "C:\Users\Xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\sentistrength\__init__.py", line 40, in getSentiment senti_score = list(map(float, senti_score)) ValueError: could not convert string to float:`
> 
> Could you please tell me how to fix this error ?
> Thank you

I got same error:
`<class 'tuple'>: (<class 'ValueError'>, ValueError("could not convert string to float: 'Could'",), <traceback object at `0x7f28b7585c08>)``

but this was happened because of bad addressing of language folder path, in my case I missed a `/` at the end of path directory in linux.

**Comment by zhunhung** [comment]
Thank you for pointing it out. I've added the relevant checks. Yes indeed it has to end with a forward slash.
