### ISSUE TITLE
Always get error for the language folder

### ISSUE THREAD

**Issue by m-i-n-a-r** [zhunhung/Python-SentiStrength#6]
First of all, using the path setup explained in the readme doesn't work. When i try to set the paths for sentistrength and the language folder using

`
senti.setSentiStrengthPath('/sentistrength/SentiStrengthCom.jar')
senti.setSentiStrengthLanguageFolderPath('/sentistrength/EN/')
`

i always get 
`ValueError: SentiStrengthLanguageFolderPath is set as '/sentistrength/IT/'. Ensure it is correct and ends with a forward slash '/'  `
the path exists, so i suspect this is some other kind of issue. Any help would be much appreciated, thanks!

**Comment by zhunhung** [comment]
Hi @m-i-n-a-r, do try setting one path above the multiple language folders.

For example:

sentistrength/
    - EN/
    - IT/
    - ...
```

Set using:
`senti.setSentiStrengthLanguageFolderPath('/sentistrength/')` instead of `senti.setSentiStrengthLanguageFolderPath('/sentistrength/EN/')`

Does this work?

**Comment by m-i-n-a-r** [comment]
Thanks for the quick reply! Sadly, changing the path to a level above didn't help, i have the same error 
`ValueError: SentiStrengthLanguageFolderPath is set as '/sentistrength/'. Ensure it is correct and ends with a forward slash '/'`

my sentistrength/ folder contains the SentiStrengthCom.jar file and 2 language folders. I tried a lot of possibile solutions but nothing works. Another weird thing is that the sentistrength path never gives error, even if i write something like
`senti.setSentiStrengthPath('/wrongfolder/notsentistrength.zip')`

**Comment by zhunhung** [comment]
Let me try on a new machine and update here again. Once again sorry for the trouble!

**Comment by zhun-tvlk** [comment]
Hi @m-i-n-a-r ,

I've tried setting up on a new machine and it works. I think the issue might lie with the path you specified.

Your code:

```
senti.setSentiStrengthPath('/sentistrength/SentiStrengthCom.jar') senti.setSentiStrengthLanguageFolderPath('/sentistrength/EN/')
```

The idea is correct, however instead of `'/sentistrength/EN/'`, try providing the absolute path instead of the relative path. This applies for both the jar file and language folder.

Do give it a try and let me know if it works.

**Comment by zhunhung** [comment]
Hi @m-i-n-a-r ,

I've tried setting up on a new machine and it works. I think the issue might lie with the path you specified.

Your code:

```
senti.setSentiStrengthPath('/sentistrength/SentiStrengthCom.jar') 

senti.setSentiStrengthLanguageFolderPath('/sentistrength/EN/')
```

The idea is correct, however instead of `'/sentistrength/EN/'`, try providing the absolute path instead of the relative path. This applies for both the jar file and language folder.

Do give it a try and let me know if it works.

**Comment by m-i-n-a-r** [comment]
I didn't provide the absolute path because i have to run the script on different machines in different paths, but i tried the solution you mentioned, here is my code now:

`
senti.setSentiStrengthPath('C:/Users/minar/Documents/MasterDegree/Thesis/sentistrength/SentiStrengthCom.jar')

senti.setSentiStrengthLanguageFolderPath('C:/Users/minar/Documents/MasterDegree/Thesis/sentistrength/IT/')
`

And, sadly, i have the same exact error on the language folder. I also tried a mix of the two solutions you gave me with no luck. I realy don't know what's the issue, i checked the paths twice.
I'm on a Window 10 machine, a Surface Pro 4.

**Comment by lambertrego** [comment]
i am also getting same error as mentioned by m-i-n-a-r . i have tried using absolute path but no luck.

**Comment by lambertrego** [comment]
I removed the value exception around ( senti_score = list(map(float, senti_score))   ) . Now its working fine.

**Comment by zhunhung** [comment]
@lambertrego great thank you! Can you help raise a PR? :)

**Comment by amirh2079** [comment]
> i am also getting same error as mentioned by m-i-n-a-r . i have tried using absolute path but no luck.
> The assertion triggers in **init**.py in the line:
> senti_score = list(map(float, senti_score))

can you please help me, i'm getting same error, can you send me your code please
