### ISSUE TITLE
About the score normalized between -1 and 1

### ISSUE THREAD

**Issue by chgferreira** [zhunhung/Python-SentiStrength#8]
Hey,

Thank you for sharing this code. Indeed, it is very useful. 
I have a doubt: Is there some paper that supports the normalized score (-1 to 1) implemented by you?
If so, could you share it with me?

Thank you again,
Best,
Carlos

**Comment by zhunhung** [comment]
Hi @chgferreira,

That's a very good point. I previously normalized it for a separate project. I've reverted it back to -4 to 4 for scale option. Thanks for pointing it out!

**Comment by chgferreira** [comment]
Hey Zhun,

Thank you for your answer.

Best,
Carlos
