### ISSUE TITLE
weird effect when working in IDE.

### ISSUE THREAD

**Issue by opendatasurgeon** [zhunhung/Python-SentiStrength#9]
Hello, 

If I am in Spyder4 (anaconda 3) IDE and follow the documentation, unfortunately this command:

```
>>> from sentistrength import PySentiStr
>>> senti = PySentiStr()
>>> result = senti.getSentiment('What a lovely day')
>>> print(result)
```
yields `[1]` . BUT, if pass in the `score='dual'` parameter, the i get the output: `[(2, -1)]`. Note that, the parameters `score='scale'` or `score='binary'` also output  `[1]`. However `score='trinary'` outputs to- `[(2, -1, 1)]`

Interesting thing is that, in Jupyter Notebook everything seems to work as you shown in your documentation. Do you think some documentation change is needed? Or it is IDE that's causing some issues?

Thanks!

**Comment by zhunhung** [comment]
Hi @opendatasurgeon, unfortunately I am unable to replicate the issue that you face. Perhaps you can provide more details on your setup?

**Comment by mihirp161** [comment]
Hello @zhunhung , we had to use `score= trinary` so everything went well. The project has ended too, and I no longer have access to the materials I worked on, therefore, I can't provide any more details. 

Appreciate you're looking into this matter though. Have a great day!

**Comment by zhunhung** [comment]
Glad to hear @opendatasurgeon , apologies for the late response! Have a great day too!
